---
sidebar: sidebar 
permalink: faq_cloud_compliance.html 
keywords: faq, frequently asked questions, questions 
summary: 如果您只是在寻找一个问题的快速答案，此常见问题解答将会有所帮助。 
---
= 有关云合规性的常见问题解答
:hardbreaks:
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
如果您只是在寻找一个问题的快速答案，此常见问题解答将会有所帮助。



== 什么是云合规性？

Cloud Compliance 是一款全新的 NetApp 云产品。借助人工智能（ AI ）驱动的技术，云合规性可帮助企业了解数据环境，并识别 AWS 或 Azure 中托管的 Cloud Volumes ONTAP 系统中的敏感数据。

云合规性提供了预定义的参数（例如敏感信息类型和类别），用于满足有关数据隐私和敏感度的新数据合规性法规，例如 GDPR ， CCPA 等。



== 为什么要使用 Cloud Compliance ？

云合规性可以为您提供数据，帮助您：

* 遵守数据合规性和隐私法规。
* 遵守数据保留策略。
* 根据 GDPR ， CCPA 和其他数据隐私法规的要求，轻松找到并报告特定数据以响应数据主题。




== Cloud Compliance 的常见用例有哪些？

* 识别个人身份信息（ PiII ）。
* 根据 GDPR 和 CCPA 隐私法规的要求确定广泛的敏感信息。
* 遵守新的和即将出台的数据隐私法规。


https://cloud.netapp.com/cloud-compliance["了解有关 Cloud Compliance 用例的更多信息"^]。



== 可以使用 Cloud Compliance 扫描哪些类型的数据？

Cloud Compliance 支持通过 NFS 和 CIFS 协议扫描非结构化数据。目前，云合规性会扫描由 Cloud Volumes ONTAP 管理的数据。

link:concept_cloud_compliance.html#how-scans-work["了解扫描的工作原理"]。



== 支持哪些云提供商？

Cloud Compliance 作为 Cloud Manager 的一部分运行，目前支持 AWS 和 Azure 。这样，您的组织就可以在不同的云提供商之间实现统一的隐私可见性。不久将增加对 Google Cloud Platform （ GCP ）的支持。



== 如何访问 Cloud Compliance ？

Cloud Compliance 通过 Cloud Manager 进行操作和管理。您可以从 Cloud Manager 中的 * 合规性 * 选项卡访问云合规性功能。



== 云合规性的工作原理是什么？

云合规部除了部署 Cloud Manager 系统和 Cloud Volumes ONTAP 实例之外，还部署了另一层人工智能。然后，它会扫描 Cloud Volumes ONTAP 上的数据，并为找到的数据洞察力编制索引。

link:concept_cloud_compliance.html["详细了解 Cloud Compliance 的工作原理"]。



== 云合规性的成本是多少？

云合规性作为 Cloud Volumes ONTAP 的一部分提供，不需要任何额外成本。将来，自定义功能可能需要额外成本。


NOTE: Cloud Compliance 要求在云提供商中部署一个实例，您的云提供商将为此实例付费。



== Cloud Compliance 扫描我的数据的频率如何？

数据经常更改，因此 Cloud Compliance 会持续扫描您的数据，而不会影响您的数据。虽然数据的初始扫描可能需要较长时间，但后续扫描只会扫描增量更改，从而缩短系统扫描时间。

link:concept_cloud_compliance.html#how-scans-work["了解扫描的工作原理"]。



== Cloud Compliance 是否提供报告？

是的。Cloud Compliance 提供的信息可能与您组织中的其他利益相关方相关，因此我们可以帮助您生成报告以分享这些见解。

以下报告可用于 Cloud Compliance ：

隐私风险评估报告:: 根据您的数据提供隐私洞察力并获得隐私风险得分。 link:task_generating_compliance_reports.html["了解更多信息。"]。
数据主体访问请求报告:: 用于提取包含数据主体的特定名称或个人标识符相关信息的所有文件的报告。 link:task_responding_to_dsar.html["了解更多信息。"]。
报告特定信息类型:: 我们提供的报告包含有关包含个人数据和敏感个人数据的已识别文件的详细信息。您还可以查看按类别和文件类型细分的文件。 link:task_controlling_private_data.html["了解更多信息。"]。




== 要实现云合规性，需要哪种类型的实例或虚拟机？

* 在 Azure 中， Cloud Compliance 在具有 512 GB 磁盘的 Standard_d16s_v3 VM 上运行。
* 在 AWS 中， Cloud Compliance 在具有 500 GB IO1 磁盘的 m5.4xlarge 实例上运行。
+
在 m5.4xlarge 不可用的区域中， Cloud Compliance 会在 m4.4xlarge 实例上运行。



link:concept_cloud_compliance.html["详细了解 Cloud Compliance 的工作原理"]。



== 扫描性能是否有所不同？

扫描性能可能因网络带宽和云环境中的平均文件大小而异。



== 如何启用云合规性？

您可以在创建新的工作环境时启用 Cloud Compliance 。您可以从 * 合规性 * 选项卡（仅限首次激活时）或通过选择特定的工作环境在现有工作环境中启用它。

link:task_getting_started_compliance.html["了解如何开始使用"]。


NOTE: 激活 Cloud Compliance 会立即执行初始扫描。之后不久将显示合规性结果。



== 如何禁用 Cloud Compliance ？

选择单个工作环境后，您可以从 " 工作环境 " 页面禁用 Cloud Compliance 。

link:task_managing_compliance.html["了解更多信息。"]。


NOTE: 要完全删除 Cloud Compliance 实例，您可以从云提供商的门户手动删除 Cloud Compliance 实例。



== 如果在 Cloud Volumes ONTAP 上启用了数据分层，会发生什么情况？

您可能希望在 Cloud Volumes ONTAP 系统上启用云合规性，以便将冷数据分层到对象存储。如果启用了数据分层，则 Cloud Compliance 会扫描所有数据—磁盘上的数据以及分层到对象存储的冷数据。

合规性扫描不会加热冷数据，它会保持冷数据并分层到对象存储。



== 是否可以使用云合规性扫描内部 ONTAP 存储？

否Cloud Compliance 目前作为 Cloud Manager 的一部分提供，并支持 Cloud Volumes ONTAP 。我们计划通过 Cloud Volumes Service 和 Azure NetApp Files 等其他云产品支持云合规性。 



== Cloud Compliance 是否可以向我的组织发送通知？

不可以，但您可以下载状态报告，这些报告可以在组织内部共享。



== 我是否可以根据组织的需求自定义服务？

Cloud Compliance 提供对数据的即装即用洞察力。您可以根据组织的需求提取和利用这些洞察信息。



== 我是否可以将云合规性信息限制为特定用户？

是的， Cloud Compliance 与 Cloud Manager 完全集成。Cloud Manager 用户只能根据其工作空间权限查看其有资格查看的工作环境的信息。

link:concept_cloud_compliance.html#user-access-to-compliance-information["了解更多信息。"]。
