---
sidebar: sidebar 
permalink: reference_networking_azure.html 
keywords: networking, network, requirements, connection, connections, vnet, security group, security groups, subnet, vpn, internet, proxy, HTTP, private, proxy server, routing, firewall, autosupport, connection, jump host, outbound, ports, blob, service endpoint 
summary: 设置 Azure 网络，以便 Cloud Volumes ONTAP 系统可以正常运行。 
---
= Azure 中的 Cloud Volumes ONTAP 的网络要求
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
设置 Azure 网络，以便 Cloud Volumes ONTAP 系统可以正常运行。

Cloud Volumes ONTAP 的出站 Internet 访问:: Cloud Volumes ONTAP 要求出站 Internet 访问向 NetApp AutoSupport 发送消息、 NetApp AutoSupport 主动监控存储的运行状况。
+
--
路由和防火墙策略必须允许通过 HTTP/HTTPS 流量访问以下端点，以便 Cloud Volumes ONTAP 可以发送 AutoSupport 消息：

* https://support.netapp.com/aods/asupmessage
* https://support.netapp.com/asupprod/post/1.0/postAsup


--
安全组:: 您不需要创建安全组，因为 Cloud Manager 可以为您提供这些功能。如果您需要使用自己的，请参见 link:reference_security_groups_azure.html["安全组规则"]。
IP 地址数:: Cloud Manager 会将以下数量的 IP 地址分配给 Azure 中的 Cloud Volumes ONTAP ：
+
--
* 单个节点： 5 个 IP 地址
* HA 对： 16 个 IP 地址
+
请注意， Cloud Manager 会在 HA 对上创建 SVM 管理 LIF ，但不会在 Azure 中的单节点系统上创建。

+

TIP: LIF 是与物理端口关联的 IP 地址。SnapCenter 等管理工具需要 SVM 管理 LIF 。



--
从 Cloud Volumes ONTAP 连接到 Azure Blob 存储以进行数据分层:: 如果要将冷数据分层到 Azure Blob 存储，只要 Cloud Manager 具有所需权限，您就无需在性能层和容量层之间设置连接。如果 Cloud Manager 策略具有以下权限，则 Cloud Manager 将为您启用 vNet 服务端点：
+
--
[source, json]
----
"Microsoft.Network/virtualNetworks/subnets/write",
"Microsoft.Network/routeTables/join/action",
----
这些权限包含在最新版本中 https://mysupport.netapp.com/cloudontap/iampolicies["Cloud Manager 策略"]。

有关设置数据分层的详细信息，请参见 link:task_tiering.html["将冷数据分层到低成本对象存储"]。

--
连接到其他网络中的 ONTAP 系统:: 要在 Azure 和 ONTAP 系统中的 Cloud Volumes ONTAP 系统之间复制数据、您必须在 Azure VNet 和其他网络之间建立 VPN 连接—例如 AWS VPC 或您的公司网络。
+
--
有关说明，请参见 https://docs.microsoft.com/en-us/azure/vpn-gateway/vpn-gateway-howto-site-to-site-resource-manager-portal["Microsoft Azure 文档：在 Azure 门户中创建站点到站点连接"^]。

--

